import { ArrowLeft, ArrowRight, Check, LockKeyhole, Mail, UserRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import "./localWorkspace.css";

const sessionKey = "globetrotter-local-session";
const profileKey = "globetrotter-local-workspace-profile";
const accountsKey = "globetrotter-local-accounts";

export default function LocalAuth() {
  const [, setLocation] = useLocation();
  const [mode, setMode] = useState<"login" | "signup" | "forgot">("login");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!email.includes("@")) return setMessage("Enter a valid email address."); const accounts = JSON.parse(localStorage.getItem(accountsKey) || "[]") as { name: string; email: string; password: string }[]; if (mode !== "forgot" && password.length < 6) return setMessage("Use at least six characters for the local password."); if (mode === "forgot") return setMessage(accounts.some(account => account.email.toLowerCase() === email.toLowerCase()) ? "A reset note is ready for this demo account. Sign in with its saved local password." : "No local account exists for this email yet."); if (mode === "signup") { if (accounts.some(account => account.email.toLowerCase() === email.toLowerCase())) return setMessage("An account with this email already exists. Please sign in."); const label = name.trim() || email.split("@")[0]; localStorage.setItem(accountsKey, JSON.stringify([...accounts, { name: label, email, password }])); localStorage.setItem(sessionKey, JSON.stringify({ name: label, email })); const current = JSON.parse(localStorage.getItem(profileKey) || "{}"); localStorage.setItem(profileKey, JSON.stringify({ ...current, name: label, email, language: current.language || "English" })); return setLocation("/local"); } const account = accounts.find(item => item.email.toLowerCase() === email.toLowerCase() && item.password === password); if (!account) return setMessage("Email or password does not match a local account. Create an account first."); localStorage.setItem(sessionKey, JSON.stringify({ name: account.name, email: account.email })); const current = JSON.parse(localStorage.getItem(profileKey) || "{}"); localStorage.setItem(profileKey, JSON.stringify({ ...current, name: account.name, email: account.email, language: current.language || "English" })); setLocation("/local"); };
  return <main className="local-auth"><Link href="/" className="text-link"><ArrowLeft size={16}/> Back to inspiration</Link><section><div className="local-auth-copy"><p className="eyebrow">YOUR TRAVEL NOTEBOOK</p><h1>Keep the good<br/><em>ideas close.</em></h1><p>This ZIP includes a browser-local account for testing every core flow. A production account uses the provided OAuth and database configuration.</p></div><form className="local-auth-form" onSubmit={submit}><p className="eyebrow">{mode === "signup" ? "CREATE YOUR DESK" : mode === "forgot" ? "RESET NOTE" : "WELCOME BACK"}</p><h2>{mode === "signup" ? <>Make a <em>first mark.</em></> : mode === "forgot" ? <>Find your <em>way back.</em></> : <>Open your <em>desk.</em></>}</h2>{mode === "signup" && <label><UserRound size={15}/> Your name<input value={name} onChange={event => setName(event.target.value)} required /></label>}<label><Mail size={15}/> Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label>{mode !== "forgot" && <label><LockKeyhole size={15}/> Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} minLength={6} required /></label>}{message && <p className="local-auth-message"><Check size={15}/>{message}</p>}<button className="ink-button" type="submit">{mode === "signup" ? "Create local account" : mode === "forgot" ? "Request reset" : "Sign in locally"}<ArrowRight size={16}/></button><div className="local-auth-switch">{mode === "login" ? <><button type="button" onClick={() => { setMode("signup"); setMessage(""); }}>Create an account</button><button type="button" onClick={() => { setMode("forgot"); setMessage(""); }}>Forgot password?</button></> : <button type="button" onClick={() => { setMode("login"); setMessage(""); }}>Back to sign in</button>}</div></form></section></main>;
}
